### ISSUE TITLE
我只想验证OFD文件是否正常，有什么好的办法？

### ISSUE THREAD

**Issue by gzchoice** [renoyuan/easyofd#11]
我有一堆OFD文件，其中有一些是打不开的，想做个python小程序来把打不开的OFD文件挑出来，请问用您的这个库能不能快速的辨别出来呢？谢谢

**Comment by renoyuan** [comment]
两种情况
第一文件本身损坏了：
你用easyodf  读取，有结果则是正常的，没有则异常

第二 ofd文件在不同工具或者代码库中兼容性不同：
这个需要看你是用什么工具打开的，因为不同工具对OFD文件协议的支持可能不同（这个协议16年之后就没有更新过了，可能一些厂家有自己的理解生成的ofd 并没严格按照协议来做，其他家的就不支持了)。
目前有遇到过一些，我这个库可以读取但其他库不能读取，WPS 可以读取其他工具或者库都不能打开，反之也有。

**Comment by gzchoice** [comment]
好的，谢谢，测试了一下，暂时解决问题
![QQ截图20240428161237](https://github.com/renoyuan/easyofd/assets/39383799/72db3593-e1dd-486f-be1a-56581819eac4)

**Comment by gzchoice** [comment]
可以了，谢谢
![image](https://github.com/renoyuan/easyofd/assets/39383799/7efe4a76-01ee-4016-a6d1-d7e759074c2e)
