### ISSUE TITLE
ofd转成pdf，盖的红章消失

### ISSUE THREAD

**Issue by maclechan** [renoyuan/easyofd#14]
<img width="491" alt="image" src="https://github.com/renoyuan/easyofd/assets/9345761/ac0ff685-df25-4d8f-86cc-08701e1d91fe">
源文件.ofd，里面有盖的红章，转成pdf之后，没有红章了

**Comment by renoyuan** [comment]
正常图片类型的签章应该是没有问题了。你这个文件我看了，里面的签章是个加密文件，这个我要先研究下它是啥加密算法，能否本地解码出来文件才能去转换pdf，你知道的话或者也可以告诉我一下，这个挺有意思的有空我会去优化下。

**Comment by renoyuan** [comment]
版本更新了，支持电子签章
