### ISSUE TITLE
OFD文件一个Cell中有多行时报错

### ISSUE THREAD

**Issue by victor10292** [renoyuan/easyofd#28]
您好，

将ofd转化为pdf时，有些文件会报如下的错误。
![error](https://github.com/user-attachments/assets/4a1cdae3-b882-4418-8b29-48085016c25e)

检查OFD文件后发现问题在于一个Cell中的文字分了两行，返回的文本是一个数组，而程序当作字典类型来处理，相关信息见附件。所以报了错。请问可以修复一下吗？谢谢。
![original file](https://github.com/user-attachments/assets/d715e4e9-334c-47d6-95df-44a3ffe89892)

![code](https://github.com/user-attachments/assets/1b1877c1-b406-435e-a01e-8369df51829c)

**Comment by renoyuan** [comment]
文件发我下

**Comment by victor10292** [comment]
文件信息比较敏感，不是很方便发

**Comment by renoyuan** [comment]
数据脱敏，或fork 后维护你的版本？

**Comment by victor10292** [comment]
我对ofd的规范不是很了解，我能把解开后的xml脱敏后打包给你吗？这样还能还原成ofd文件吗？Sent from my iPhoneOn Sep 4, 2024, at 16:52, 貌似大家 ***@***.***> wrote:﻿
数据脱敏，或fork 后维护你的版本？

**Comment by victor10292** [comment]
附件是去掉敏感信息后的源文件。
[sample.zip](https://github.com/user-attachments/files/16882234/sample.zip)

**Comment by renoyuan** [comment]
已更新

**Comment by victor10292** [comment]
收到，问题解决了，如果把调试用的print语句去掉就更好了。
