### ISSUE TITLE
ofd转换成pdf后，文字会重叠

### ISSUE THREAD

**Issue by ZGuangW** [renoyuan/easyofd#9]
ofd转换成pdf后，文字会重叠
![image](https://github.com/renoyuan/easyofd/assets/8532392/a6e134b7-8040-4f85-b4cd-e8d6066d94af)
![image](https://github.com/renoyuan/easyofd/assets/8532392/bc27a86b-33f1-4f05-992b-3b31d8ffc4b5)

**Comment by renoyuan** [comment]
ofd文件发来看看

**Comment by ZGuangW** [comment]
好的，请查收附件

________________________________
发件人: 貌似大家 ***@***.***>
发送时间: 2024年4月10日 17:33
收件人: renoyuan/easyofd ***@***.***>
抄送: ZGuangW ***@***.***>; Author ***@***.***>
主题: Re: [renoyuan/easyofd] ofd转换成pdf后，文字会重叠 (Issue #9)


ofd文件发来看看

―

**Comment by ZGuangW** [comment]
[测试.zip](https://github.com/renoyuan/easyofd/files/14931352/default.zip)
这个文件

**Comment by renoyuan** [comment]
![image](https://github.com/renoyuan/easyofd/assets/50486789/c4fc03e9-5b75-4db6-a3b7-6c5172549ae2)
已修复
